version: '3.8'
services:
  tt-db:
    container_name: tt-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: tt-user
    ports:
      - "5330:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tt

  tt-app:
    container_name: tt-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - tt-db
    networks:
      - tt

volumes:
  postgres_data:

networks:
  tt:
    driver: bridge
